# Release Drafter config
name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
exclude-labels:
  - 'skip-changelog'
  - 'internal'
  - 'duplicate'
  - 'invalid'
  - 'wontfix'
categories:
  - title: '💥 Breaking Changes'
    labels:
      - 'breaking-change'
      - 'breaking'
      - 'major'
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
      - 'regression'
  - title: '🔒 Security'
    labels:
      - 'security'
      - 'vulnerability'
  - title: '⚡ Performance'
    labels:
      - 'performance'
      - 'optimization'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'refactor'
      - 'deps'
      - 'dependencies'
  - title: '🤖 CI/CD'
    labels:
      - 'ci'
      - 'cd'
      - 'workflow'
      - 'github-actions'
  - title: '📝 Documentation'
    labels:
      - 'docs'
      - 'documentation'
  - title: '🧪 Testing'
    labels:
      - 'test'
      - 'testing'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
no-changes-template: '- No changes in this release'
template: |
  ## What's Changed

  $CHANGES

  ## Contributors

  Thanks to $CONTRIBUTORS for contributing to this release!

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking-change'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'patch'
      - 'bug'
      - 'fix'
      - 'chore'
      - 'deps'
      - 'docs'
  default: patch

autolabeler:
  - label: 'breaking-change'
    title:
      - '/break/i'
      - '/\bbreaking\b/i'
  - label: 'security'
    title:
      - '/security/i'
      - '/vulnerability/i'
      - '/\bcve\b/i'
  - label: 'performance'
    title:
      - '/perf/i'
      - '/performance/i'
      - '/optimi[sz]e/i'
  - label: 'docs'
    files:
      - '**/*.md'
      - '**/docs/**/*'
    title:
      - '/docs?:/i'
      - '/documentation/i'
  - label: 'deps'
    title:
      - '/deps?:/i'
      - '/dependency/i'
      - '/dependencies/i'
      - '/bump/i'
    branch:
      - '/dependabot/.+/'
      - '/renovate/.+/'
    files:
      - 'package.json'
      - 'package-lock.json'
  - label: 'test'
    files:
      - '**/test/**/*'
      - '**/*.test.js'
      - '**/*.spec.js'
    title:
      - '/test:/i'
      - '/testing/i'
  - label: 'ci'
    files:
      - '.github/workflows/**/*'
      - '.github/**/*.yml'
      - '.github/**/*.yaml'
    title:
      - '/\bci\b/i'
      - '/workflow/i'
      - '/github actions/i'
  - label: 'bug'
    title:
      - '/fix:/i'
      - '/\bbug\b/i'
      - '/fixes #\d+/i'
  - label: 'enhancement'
    title:
      - '/feat:/i'
      - '/feature:/i'
      - '/enhance/i'
  - label: 'chore'
    title:
      - '/chore:/i'
      - '/refactor:/i'

prerelease: false

replacers:
  - search: '/\[bot\]/'
    replace: ''
  - search: '/dependabot/i'
    replace: 'Dependabot'